### ISSUE TITLE
Markdown rendering of bullet lists

### ISSUE THREAD

**Issue by amotl** [Daemonite/discourse-material-theme#13]
# Problem
When rendering a markdown bullet list, no margin is applied after the last item.

### Input
```
Hello
- one
- two
- three

world!
```

### Output: GitHub renderer
Hello
- one
- two
- three

world!

### Output: Discourse with Default theme
![image](https://user-images.githubusercontent.com/453543/51083818-76246600-1720-11e9-92e4-58e84b690beb.png)

### Output: Discourse with Daemonite Material theme
![image](https://user-images.githubusercontent.com/453543/51083819-791f5680-1720-11e9-9b4f-127c108d67d0.png)

**Comment by sesemaya** [comment]
Discourse resets the styles (mostly`font-size`s and `margin`s) of some common elements in `.cooked` and `.d-editor-preview`. 3c29660 re-applies the default `font-size` and `margin` back on these elements.

**Comment by amotl** [comment]
Thanks @sesemaya!

We recognize the intrinsic details required to be taken care of when implementing such fixes for real with Sass, in comparison to our [humble tweaks](https://github.com/ip-tools/discourse-material-theme-ample/blob/master/common/common.scss) we made mostly on the CSS level for ad hoc fixing some things we are listing here. Sorry that we won't be of any help for you resolving the various filed issues on the expert level until possibly reading more on the commit stream and doing hands-on work with Sass ourselves. So, thanks again for taking care!

If you **do** like the reports we are making in order to eventually assist with further teeth cutting of this excellent theme by also looking at the nitty gritty details and you feel the time is right for this, please let us know.

Saying that, sorry in retrospective for the bulk-filing of some of the issues. We thought it would be a good idea to have them separated from each other but actually didn't ask before what your preferred way would look like. The reason we chose GitHub was that we didn't want to clutter [the Discourse topic](https://meta.discourse.org/t/daemonite-material-theme/64521) with our ramifications.
